### ISSUE TITLE
XXL-JOB升级方案(2.0.1 -> 2.0.2)

### ISSUE THREAD

**Issue by xumeng** [xuxueli/xxl-job#1038]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1 -> 2.0.2
#### 升级过程
1. 数据库：
    修改表结构，增加字段和索引
```sql
ALTER TABLE `XXL_JOB_QRTZ_TRIGGER_LOG` 
ADD COLUMN `alarm_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败' AFTER `handle_msg`,
ADD INDEX `I_handle_code`(`handle_code`) USING BTREE;
```
2. 调度中心：
    修改 xxl-job-{env}.yml 中的配置(或者 application 配置文件)，添加 spring datasource 和 spring mail 配置
```yaml
spring.datasource.tomcat.validation-query: SELECT 1
spring.datasource.tomcat.validation-interval: 30000
```
```yaml
spring.mail.host: smtp.xx.com
spring.mail.port: xx
spring.mail.username: xxxx@xx.com
spring.mail.password: xxxx
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
```

3. 嵌入 task 的业务项目或者 executor：

    升级 pom 文件中 xxl-job 依赖版本号为 2.0.2

#### 升级问题
1. 问题：升级后，查看任务日志一直显示`处理中`
    解决方案：经查日志，是没有修改表结构`XXL_JOB_QRTZ_TRIGGER_LOG`，按照上文中添加字段和索引即可

2. 问题：升级后，查看任务列表任务显示 `stop ` 状态，但任务日志仍然在增加，表明任务仍然处于运行状态
    解决方案：经排查，删除 `XXL_JOB_QRTZ_CRON_TRIGGERS ` 表的数据。下面为详细解决方案。

   > 建议删除之前先把所有的表中数据备份。
   > 试一下删除这三张表数据，任务启动的执行周期和设定会记录在这三张表中：
   > XXL_JOB_QRTZ_CRON_TRIGGERS
   > XXL_JOB_QRTZ_JOB_DETAILS
   > XXL_JOB_QRTZ_TRIGGERS
   > 清空数据之前最好先记录下哪些任务是已启动需要跑的任务，避免遗忘。

参考 issue： #918
