### ISSUE TITLE
[consult] 新手上路, docker 部署

### ISSUE THREAD

**Issue by Alice52** [xuxueli/xxl-job#2421]
### Which version of XXL-JOB do you using?

- V2.3.0

### Expected behavior

1. deploy `xxl-admin` in docker and container_name is `dev-xxl-job-admin`
2. How to fill `xxl.job.admin.address` when admin built by docker used in exector? Compose file is below.

```yml
services:
  xxl-job-admin:
    image: xx/xxl-job-admin:2.3.1
    restart: 'on-failure:3'
    container_name: dev-xxl-job-admin
    ports:
      - 9090:8080
     
  
  xxl-job-executor:
    image: /**/boot-job-xxl-job:20210516.5c6e021
    restart: 'on-failure:3'
    container_name: dev-xxl-job-executor
    ports:
      - 9091:8080
      
# And I config `xxl.job.admin.address` to  http://dev-xxl-job-admin:9090/xxl-job-admin, but it will throw connection exception 
# with `xxl-rpc remoting error(Connection refused (Connection refused)), for url : http://dev-xxl-job-admin:9090/xxl-job-admin/api/registry, content=null` message when executor start-up.
```

3. Why can't it be configured like this?

### Actual behavior

1. I want it can register and discovery by `container_name`

@xuxueli @thinkingfioa  Please help me out this trouble, thanks.
