### ISSUE TITLE
v2.3.0  job handler [ ] not found.

### ISSUE THREAD

**Issue by wuyuelearning** [xuxueli/xxl-job#2493]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v.2.3.0

### Expected behavior
注册使用调度功能

### Actual behavior

job handler [demoJobHandler3] not found.

### Steps to reproduce the behavior

springboot  2.5.1 和2.3.1.RELEASE 都试了

1、在本地运行官方xxl-job-admin (2.3.1-SNAPSHOT版本)，可以打开控制台界面，运行官方demo中的executor工程能注册、调用
2、另一个项目中加入XxlJobconfig文件
```
@Configuration
 public XxlJobSpringExecutor xxlJobExecutor() {
        logger.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppname(appName);
        xxlJobSpringExecutor.setAddress(address);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);
        return xxlJobSpringExecutor;
    }

```
pom.xml文件
```
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.3.0</version>
        </dependency>
```
配置文件
```
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8087/xxl-job-admin   
    executor:
      appName: mydemo
      ip:
      port: 9999
      logPath: /data/applogs/xxl-job/jobhandler
      logRetentionDays: 30
      address:
    accessToken:
```

使用：
```
@Component
public class JobHandler {
    @XxlJob("demoJobHandler3")
    public void demoJobHandler3(){
    }
}
```

控制台可以正常自动注册，但是调用的时候报错
job handler [demoJobHandler3] not found.

### Other information

1、当出现两个相同的
 @XxlJob("demoJobHandler3")，springboot启动没有报错
用v2.2.0版本会报错

2、使用v2.2.0 可以正常调度
