### ISSUE TITLE
xxl-job如何接入K8S

### ISSUE THREAD

**Issue by cy930707** [xuxueli/xxl-job#2521]
请问XXL-JOB如何接入K8S，K8S+Docker是容器化部署，xxl的jobhandler是根据IP就行区分节点的。容器化后没有了IP，请教一下这一步的一个操作思路。能给出一些简短的文字叙述解决方案就好，谢谢！

**Comment by zjwon** [comment]
把xxl-job-admin打包成docker镜像，然后用这个镜像创建deployment和service，service会有集群IP，如果是内网环境，执行器直接使用service的集群IP，如果想外网使用，可以使用ingress进行暴露

**Comment by zjwon** [comment]
把xxl-job-admin打包成docker镜像，然后用这个镜像创建deployment和service，service会有集群IP，如果是内网环境，执行器直接使用service的集群IP，如果想外网使用，可以使用ingress进行暴露

**Comment by zjwon** [comment]
官方文档里也有现成的docker镜像
https://www.xuxueli.com/xxl-job/#%E5%85%B6%E4%BB%96%EF%BC%9ADocker%20%E9%95%9C%E5%83%8F%E6%96%B9%E5%BC%8F%E6%90%AD%E5%BB%BA%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%EF%BC%9A
![image](https://user-images.githubusercontent.com/12381829/126626866-fddcc784-fb95-4f6d-ad06-1a2f2f1d4271.png)

**Comment by cy930707** [comment]
> 官方文档里也有现成的docker镜像
> https://www.xuxueli.com/xxl-job/#%E5%85%B6%E4%BB%96%EF%BC%9ADocker%20%E9%95%9C%E5%83%8F%E6%96%B9%E5%BC%8F%E6%90%AD%E5%BB%BA%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%EF%BC%9A
> ![image](https://user-images.githubusercontent.com/12381829/126626866-fddcc784-fb95-4f6d-ad06-1a2f2f1d4271.png)

谢谢

**Comment by cy930707** [comment]
> 官方文档里也有现成的docker镜像
> https://www.xuxueli.com/xxl-job/#%E5%85%B6%E4%BB%96%EF%BC%9ADocker%20%E9%95%9C%E5%83%8F%E6%96%B9%E5%BC%8F%E6%90%AD%E5%BB%BA%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%EF%BC%9A
> ![image](https://user-images.githubusercontent.com/12381829/126626866-fddcc784-fb95-4f6d-ad06-1a2f2f1d4271.png)

大佬，我想问下，端口问题。这个端口还需要k8s单独开放一个嘛

**Comment by zjwon** [comment]
> > 官方文档里也有现成的docker镜像
> > https://www.xuxueli.com/xxl-job/#%E5%85%B6%E4%BB%96%EF%BC%9ADocker%20%E9%95%9C%E5%83%8F%E6%96%B9%E5%BC%8F%E6%90%AD%E5%BB%BA%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%EF%BC%9A
> > ![image](https://user-images.githubusercontent.com/12381829/126626866-fddcc784-fb95-4f6d-ad06-1a2f2f1d4271.png)
> 
> 大佬，我想问下，端口问题。这个端口还需要k8s单独开放一个嘛

Service建好后会有集群IP和映射到节点的端口，以下面的yaml配置为例，集群内部访问xxl-job-admin的地址就是：集群IP:28080
```
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin-svc
  namespace: default
spec:
  ports:
    - name: port
      port: 28080
      protocol: TCP
      targetPort: 8080
  selector:
    app: xxl-job-admin
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xxl-job-admin
  name: xxl-job-admin
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xxl-job-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: JAVA_HOME
              value: /docker-java-home/jre
            - name: PARAMS
              value: xxxxxxxxxxx数据库连接参数xxxxxxxxxxxx
            - name: TZ
              value: PRC
          image: xxxxxxxxxxx镜像地址xxxxxxxxxxx
          imagePullPolicy: Always
          name: xxl-job-admin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxl-job-admin-ingress
  namespace: default
spec:
  rules:
    - host: xxxxx域名xxxxx
      http:
        paths:
          - backend:
              serviceName: xxl-job-admin-svc
              servicePort: 28080
            path: /
            pathType: ImplementationSpecific      
```
