### ISSUE TITLE
执行器调度不均问题

### ISSUE THREAD

**Issue by BennyTian** [xuxueli/xxl-job#3721]
项目部署在k8s,以pod的形式运行, 一个admin , 2个executor , 执行器自动注册

版本: 
```
<dependency>
	<groupId>com.xuxueli</groupId>
	<artifactId>xxl-job-core</artifactId>
	<version>2.3.1</version>
</dependency>
```

注册代码(application.yaml, http://xxx-job-admin:8080 这个是k8s中的service):
```
xxl:
  job:
    accessToken: xxxxxx
    admin:
      addresses: http://xxx-job-admin:8080
    executor:
      appname: xxx-job-executor
      ip: ''
      logpath: /logs/xxl-job/jobhandler
      logretentiondays: 30
      port: 8089
```

注册之后的执行器:

```
1. http://172.25.44.89:8089/
2. http://172.25.45.119:8089/
```
执行器负载(m为k8s的cpu, Mi为内存):
```
kubectl top pods --sort-by=cpu | grep job-executor

job-executor-789bdc99d-5h6mv   1851m        4612Mi          
job-executor-789bdc99d-kqztv   139m         1497Mi   
```

项目运行正常, 但是发现 2个执行器,一个cpu很高,另外一个很闲,查看了r任务调度日志, 所有任务都跑在一个执行器上,任务的调度策略配置的也都是轮询

请问 我这个是哪里配置的还有问题吗?
